import {expect, test, type APIRequestContext, type Page} from "@playwright/test";
import {mkdir} from "node:fs/promises";
import type {ScheduledSnapshot} from "../../src/tasks/scheduledTypes";
import type {WorkspaceData} from "../../src/shared/workspace";

async function cleanTasks(request: APIRequestContext) {
    await request.post("/api/auth/login", {data: {username: "2000000001", password: "fixture-password"}});
    let state = await (await request.get("/api/scheduled-tasks")).json() as ScheduledSnapshot;
    for (const run of state.runs.filter(run => run.status === "running")) await request.post("/api/scheduled-tasks/stop", {data: {id: run.id}});
    await expect.poll(async () => ((await (await request.get("/api/scheduled-tasks")).json()) as ScheduledSnapshot).runs.some(run => run.status === "running")).toBe(false);
    state = await (await request.get("/api/scheduled-tasks")).json() as ScheduledSnapshot;
    for (const run of state.runs) await request.post("/api/scheduled-tasks/delete-run", {data: {id: run.id}});
    for (const task of state.tasks) await request.post("/api/scheduled-tasks/delete", {data: {id: task.id}});
    await request.post("/api/auth/logout", {data: {}});
    await request.post("/__fixture/reset", {data: {}});
}

async function login(page: Page) {
    await page.getByRole("button", {name: /连接清华账号/}).click();
    const dialog = page.getByRole("dialog", {name: "连接清华 Info"});
    await dialog.getByLabel("学号").fill("2000000001");
    await dialog.getByLabel("密码").fill("fixture-password");
    await dialog.getByRole("button", {name: "登录", exact: true}).click();
    await expect(dialog).not.toBeVisible();
}

test.beforeEach(async ({request}) => cleanTasks(request));
test.afterEach(async ({request}) => cleanTasks(request));

test("定时任务创建、编辑、暂停、执行、历史续聊和删除", async ({page}) => {
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    await page.goto("/"); await login(page);
    await page.getByRole("button", {name: "定时任务", exact: true}).click();
    await expect(page).toHaveURL(/#tasks$/);
    await expect(page.locator(".toolbar")).toHaveCount(0);
    await page.getByRole("button", {name: "新建任务", exact: true}).click();
    let editor = page.getByRole("dialog", {name: "新建定时任务"});
    await editor.getByLabel("任务名称").fill("早间课程安排");
    await editor.getByLabel("任务内容").fill("查询今天的课程，按时间整理。");
    await editor.getByLabel("执行频率").selectOption("weekly");
    await editor.getByLabel("执行时间（北京时间）").fill("08:30");
    await editor.getByRole("button", {name: "星期二"}).click();
    await editor.getByRole("button", {name: "星期四"}).click();
    await mkdir("docs/screenshots", {recursive: true});
    await expect(page.locator(".toast")).toHaveCount(0);
    await expect(editor).toHaveCSS("opacity", "1");
    await page.screenshot({path: "docs/screenshots/web-task-editor.png", animations: "disabled"});
    await editor.getByRole("button", {name: "保存任务"}).click();
    await expect(editor).not.toBeVisible();
    const row = page.locator(".task-row").filter({hasText: "早间课程安排"});
    await expect(row).toContainText("每周一、三、五 08:30");
    await page.getByRole("button", {name: "暂停任务：早间课程安排", exact: true}).click();
    await expect(row).toContainText("已暂停");
    await page.getByRole("button", {name: "编辑任务：早间课程安排", exact: true}).click();
    editor = page.getByRole("dialog", {name: "编辑任务"});
    await editor.getByLabel("任务名称").fill("每天的课程安排");
    await editor.getByLabel("执行频率").selectOption("daily");
    await editor.getByRole("button", {name: "保存任务"}).click();
    await expect(editor).not.toBeVisible();
    await expect(page.locator(".task-row")).toContainText("每天 08:30");
    await page.getByRole("button", {name: "启用任务：每天的课程安排", exact: true}).click();
    await expect(page.locator(".task-status")).toHaveText("已启用");
    await expect(page.locator(".toast")).toHaveCount(0);
    await page.screenshot({path: "docs/screenshots/web-tasks-light.png", animations: "disabled"});
    await page.getByRole("button", {name: "新建对话"}).click();
    await page.getByRole("button", {name: "切换到深色模式"}).click();
    await expect(page.locator("html")).not.toHaveAttribute("data-theme-transition");
    await page.getByRole("button", {name: "定时任务", exact: true}).click();
    await expect(page.locator(".task-row")).toContainText("每天的课程安排");
    await page.screenshot({path: "docs/screenshots/web-tasks-dark.png", animations: "disabled"});
    await page.getByRole("button", {name: "立即运行：每天的课程安排", exact: true}).click();
    await page.getByRole("tab", {name: /执行历史/}).click();
    await expect(page.locator(".run-row .task-status")).toHaveText("已完成");
    await expect(page.getByRole("navigation", {name: "历史对话"})).not.toContainText("每天的课程安排");
    await page.screenshot({path: "docs/screenshots/web-task-history.png", animations: "disabled"});
    await page.getByRole("button", {name: "打开会话", exact: true}).click();
    await expect(page.getByText("任务会话 · 可以继续提问和处理结果")).toBeVisible();
    await expect(page.locator(".markdown table")).toBeVisible();
    await page.getByRole("textbox", {name: "发送给清灵的消息"}).fill("再帮我整理下午的安排");
    await page.getByRole("button", {name: "发送消息", exact: true}).click();
    await expect(page.locator(".markdown table")).toHaveCount(2);
    await expect(page.getByRole("button", {name: "停止生成", exact: true})).not.toBeVisible();
    await expect(page.getByRole("navigation", {name: "历史对话"})).not.toContainText("每天的课程安排");
    await page.reload();
    await expect(page.locator(".markdown table")).toHaveCount(2);
    await expect(page.getByRole("navigation", {name: "历史对话"})).not.toContainText("每天的课程安排");
    await page.getByRole("button", {name: "返回定时任务"}).click();
    await page.getByRole("button", {name: "删除任务：每天的课程安排", exact: true}).click();
    await page.getByRole("dialog", {name: "删除任务"}).getByRole("button", {name: "确认", exact: true}).click();
    await expect(page.locator(".task-row")).toHaveCount(0);
    await page.getByRole("tab", {name: /执行历史/}).click();
    await expect(page.locator(".run-row")).toHaveCount(1);
    await page.getByRole("button", {name: "删除执行记录：每天的课程安排", exact: true}).click();
    await page.getByRole("dialog", {name: "删除执行记录"}).getByRole("button", {name: "确认", exact: true}).click();
    await expect(page.locator(".run-row")).toHaveCount(0);
    expect(errors).toEqual([]);
});

test("移动端单次任务和待确认任务进入会话继续执行", async ({page}) => {
    await page.setViewportSize({width: 390, height: 844});
    await page.goto("/#tasks");
    await expect(page.getByText("连接清华账号后，创建和管理你的定时任务。")).toBeVisible();
    await page.getByRole("button", {name: "连接账号", exact: true}).click();
    const loginDialog = page.getByRole("dialog", {name: "连接清华 Info"});
    await loginDialog.getByLabel("学号").fill("2000000001");
    await loginDialog.getByLabel("密码").fill("fixture-password");
    await loginDialog.getByRole("button", {name: "登录", exact: true}).click();
    await expect(loginDialog).not.toBeVisible();
    await page.getByRole("button", {name: "新建任务", exact: true}).click();
    const editor = page.getByRole("dialog", {name: "新建定时任务"});
    await editor.getByLabel("任务名称").fill("周末图书馆预约");
    await editor.getByLabel("任务内容").fill("预约图书馆座位");
    await editor.getByLabel("执行频率").selectOption("once");
    await editor.getByLabel("执行日期").fill("2099-09-16");
    await editor.getByRole("button", {name: "保存任务"}).click();
    await expect(editor).not.toBeVisible();
    await expect(page.locator(".task-row")).toContainText("2099-09-16");
    await expect(page.locator(".toast")).toHaveCount(0);
    await page.screenshot({path: "docs/screenshots/web-tasks-mobile.png", animations: "disabled"});
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.getByRole("button", {name: "立即运行：周末图书馆预约", exact: true}).click();
    await page.getByRole("tab", {name: /执行历史/}).click();
    await expect(page.locator(".run-row .task-status")).toHaveText("待处理");
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await page.getByRole("button", {name: "打开会话", exact: true}).click();
    await page.getByRole("textbox", {name: "发送给清灵的消息"}).fill("继续预约");
    await page.getByRole("button", {name: "发送消息", exact: true}).click();
    const confirm = page.getByRole("dialog", {name: "确认这次操作"});
    await expect(confirm).toBeVisible();
    await confirm.getByRole("button", {name: "确认执行", exact: true}).click();
    await expect(page.locator(".markdown").last()).toContainText("测试预约已确认");
});

test("可以查看后台进度并停止，任务查询失败显示可重试状态", async ({page, request}) => {
    await page.goto("/"); await login(page);
    await request.post("/api/scheduled-tasks/create", {data: {title: "较长的查询", prompt: "停止时序测试", schedule: {frequency: "daily", time: "08:00"}}});
    await page.getByRole("button", {name: "定时任务", exact: true}).click();
    await page.getByRole("button", {name: "立即运行：较长的查询", exact: true}).click();
    await page.getByRole("tab", {name: /执行历史/}).click();
    await page.getByRole("button", {name: "查看进度", exact: true}).click();
    await expect(page.getByText("正在执行 · 完成后可继续对话")).toBeVisible();
    await page.getByRole("button", {name: "新建对话"}).click();
    await expect(page.getByRole("button", {name: "查看定时任务进度", exact: true})).toBeVisible();
    await page.getByRole("textbox", {name: "发送给清灵的消息"}).fill("继续");
    await expect(page.getByRole("button", {name: "发送消息", exact: true})).toBeDisabled();
    await page.getByRole("button", {name: "查看定时任务进度", exact: true}).click();
    await page.getByRole("button", {name: "返回定时任务"}).click();
    await page.getByRole("tab", {name: /执行历史/}).click();
    await page.getByRole("button", {name: "停止执行：较长的查询", exact: true}).click();
    await expect(page.locator(".run-row .task-status")).toHaveText("已停止");
    await page.getByRole("button", {name: "按当前计划再次运行：较长的查询", exact: true}).click();
    await expect(page.locator(".run-row")).toHaveCount(2);
    await page.getByRole("button", {name: "停止执行：较长的查询", exact: true}).click();
    await expect(page.locator(".run-row .task-status")).toHaveText(["已停止", "已停止"]);
    await page.route("**/api/scheduled-tasks", route => route.fulfill({status: 503, contentType: "application/json", body: JSON.stringify({error: "任务服务暂时不可用"})}));
    await page.getByRole("button", {name: "刷新任务", exact: true}).click();
    await expect(page.getByRole("alert")).toContainText("任务服务暂时不可用");
    await page.unroute("**/api/scheduled-tasks");
    await page.getByRole("button", {name: "重试", exact: true}).click();
    await expect(page.getByRole("alert")).toHaveCount(0);
});

test("服务端同步完成时间线时保留用户展开的处理过程", async ({page, request}) => {
    await page.goto("/"); await login(page);
    await page.getByRole("textbox", {name: "发送给清灵的消息"}).fill("时序：查课表");
    await page.getByRole("button", {name: "发送消息", exact: true}).click();
    await expect(page.getByRole("button", {name: "展开处理过程"})).toBeVisible();
    await expect(page.getByRole("button", {name: "停止生成", exact: true})).not.toBeVisible();
    await page.getByRole("button", {name: "展开处理过程"}).click();
    await page.locator(".reasoning-heading").first().click();
    const saved = await (await request.get("/api/workspace")).json() as WorkspaceData;
    const session = saved.history.sessions.find(session => session.id === saved.history.activeId)!;
    session.title = "已同步的时间线";
    session.messages.findLast(message => message.turn)!.turn!.startedAt += 1000;
    await page.route("**/api/workspace?revision=*", route => route.fulfill({json: saved}));
    await expect(page.locator(".workspace-title")).toHaveText("已同步的时间线");
    await expect(page.getByRole("button", {name: "收起处理过程"})).toHaveAttribute("aria-expanded", "true");
    await expect(page.getByText("先确认今天的课程，再核对空闲时段。", {exact: true})).toBeVisible();
});
